apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-pod
spec:
  containers:
    - name: configmap-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 600"]
      envFrom:
      - configMapRef:
          name: hello-world