apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod
spec:
  containers:
    - name: secret-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password